### ISSUE TITLE
PSR-0 violation

### ISSUE THREAD

**Issue by JeroenDeDauw** [ravage84/mediawiki-guzzle-json-auth#1]
`GuzzleJsonAuth.php` modifies some globals on top of defining a class. For MediaWiki extensions these globals are typically put in ExtensionName.php in the root, and then "autoloaded" in the files section ([example](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/composer.json#L69-L70)).

**Comment by ravage84** [comment]
Thanks for pointing out. Never developed with MediaWiki before the week before last.
Where would that be documented?
I was inspired by the [Typo3Auth class](http://www.mediawiki.org/wiki/Extension:Typo3Auth#Code), which seems to be quite outdated in many aspects.

**Comment by JeroenDeDauw** [comment]
I don't know if there is decent documentation about this. Not so long ago namespaces where seen as this evil thing in the MW community. And Composer still is to a big extend ;p PSR-0 is not a MW thing tho.

**Comment by ravage84** [comment]
Sure, I was aware that I violate against PSR-0. But due to the lack of _findable_ documentation, I just followed existing implementations.
That said, I think it would be greatly beneficial for the MediaWiki (extension) ecosystem if there was better documentation.
Beyond that it could help if there was a skeleton extension repo which incorporates (and optionally explains) all the best and mandatory practices for a MediaWiki extension.

Something like the PHP league skeleton repo:
https://github.com/thephpleague/skeleton

Or what I did for CakePHP plugins here:
https://github.com/ravage84/cakephp-plugin-skel/

With something like this, it would be far easier to start a MediaWiki extension.

**Comment by ravage84** [comment]
@JeroenDeDauw  done as in your example, but this actually only moves the problem away from the class to the new file:
https://scrutinizer-ci.com/g/ravage84/mediawiki-guzzle-json-auth/issues/master/files/GuzzleJsonAuth.php?orderField=path&order=asc

**Comment by JeroenDeDauw** [comment]
Oh right, this rule is actually part of PSR-1. Defining both the constant and doing the global assignment in this file indeed violates it, though IMO can easily be ignored. You can also just remove the constant if you do not actually need it. 

Do note that the global assignment is actually broken though, since the code assumes it's included from global scope, which is not the case when using the Composer autoloader. See also: http://www.bn2vs.com/blog/2013/11/24/introduction-to-composer-for-mediawiki-developers/

**Comment by ravage84** [comment]
Thanks again for pointing out.
Fixed in https://github.com/ravage84/mediawiki-guzzle-json-auth/commit/73beb8095c01e18dfc03af43dedab5868da9d241
